### ISSUE TITLE
Character editor like it was used in Psych Engine?

### ISSUE THREAD

**Issue by kubapl2004gmail** [TheWilley/FruityDancitor#11]
Can you add character editor with features like it was used in Psych Engine?
https://camo.githubusercontent.com/a33f59a7147f2d7314e07b9c5f13f41b28eda5c9dde8acf42d9af1c582057468/68747470733a2f2f692e696d6775722e636f6d2f74523035454d502e706e67

**Comment by TheWilley** [comment]
This is out of scope of this project, as the goal is to compile a sprite sheet, not edit individual frames.
